export const necklaces = [
  {
    id: "NL001",
    name: "Elegant Pearl Necklace",
    image: "/assets/necklace01.jpg",
    status: "available",
    price: 120.99,
    description: "A classic pearl necklace that adds elegance to any outfit.",
  },
  {
    id: "NL002",
    name: "Gold Chain Necklace",
    image: "/assets/necklace02.jpg",
    status: "out of stock",
    price: 150.5,
    description: "A premium 18K gold chain, perfect for everyday wear.",
  },
  {
    id: "NL003",
    name: "Silver Heart Pendant",
    image: "/assets/necklace03.jpg",
    status: "available",
    price: 75.0,
    description: "A beautiful silver necklace with a heart-shaped pendant.",
  },
  {
    id: "NL004",
    name: "Crystal Choker Necklace",
    image: "/assets/necklace04.jpg",
    status: "available",
    price: 89.99,
    description: "A stunning crystal choker that shines in the light.",
  },
  {
    id: "NL005",
    name: "Diamond Infinity Necklace",
    image: "/assets/necklace05.jpg",
    status: "available",
    price: 250.0,
    description: "An elegant infinity-shaped pendant with sparkling diamonds.",
  },
  {
    id: "NL006",
    name: "Rose Gold Layered Necklace",
    image: "/assets/necklace06.jpg",
    status: "available",
    price: 110.75,
    description: "A trendy layered necklace in rose gold for a stylish look.",
  },
  {
    id: "NL007",
    name: "Vintage Locket Necklace",
    image: "/assets/necklace07.jpg",
    status: "out of stock",
    price: 130.0,
    description:
      "A vintage-style locket necklace with a hidden photo compartment.",
  },
  {
    id: "NL008",
    name: "Minimalist Bar Necklace",
    image: "/assets/necklace08.jpg",
    status: "available",
    price: 60.99,
    description: "A sleek and simple bar necklace for a modern touch.",
  },
  {
    id: "NL009",
    name: "Bohemian Beaded Necklace",
    image: "/assets/necklace09.jpg",
    status: "available",
    price: 45.5,
    description: "A colorful bohemian necklace with intricate beadwork.",
  },
  {
    id: "NL010",
    name: "Moon & Star Pendant Necklace",
    image: "/assets/necklace10.jpg",
    status: "available",
    price: 85.0,
    description:
      "A celestial-inspired necklace featuring a moon and star pendant.",
  },
  {
    id: "NL011",
    name: "Golden Elegance",
    image: "/assets/necklace11.jpg",
    status: "available",
    price: 120.99,
    description: "A stunning gold-plated necklace with intricate detailing.",
  },
  {
    id: "NL012",
    name: "Silver Serenity",
    image: "/assets/necklace12.jpg",
    status: "out of stock",
    price: 85.5,
    description: "Elegant silver necklace with a minimalist charm.",
  },
  {
    id: "NL013",
    name: "Pearl Grace",
    image: "/assets/necklace13.jpg",
    status: "available",
    price: 150.0,
    description: "Classic pearl necklace for timeless beauty.",
  },
  {
    id: "NL014",
    name: "Ruby Radiance",
    image: "/assets/necklace14.jpg",
    status: "available",
    price: 230.75,
    description: "A luxurious ruby-embedded necklace for a royal look.",
  },
  {
    id: "NL015",
    name: "Emerald Essence",
    image: "/assets/necklace15.jpg",
    status: "available",
    price: 199.99,
    description: "An emerald gemstone necklace exuding sophistication.",
  },
  {
    id: "NL016",
    name: "Sapphire Sparkle",
    image: "/assets/necklace16.jpg",
    status: "available",
    price: 215.5,
    description: "A dazzling sapphire-adorned necklace with a radiant glow.",
  },
  {
    id: "NL017",
    name: "Diamond Delight",
    image: "/assets/necklace17.jpg",
    status: "out of stock",
    price: 350.0,
    description: "Exquisite diamond necklace for an elegant touch.",
  },
  {
    id: "NL018",
    name: "Rose Gold Charm",
    image: "/assets/necklace18.jpg",
    status: "available",
    price: 99.99,
    description: "A delicate rose gold necklace with a heart pendant.",
  },
  {
    id: "NL019",
    name: "Crystal Bloom",
    image: "/assets/necklace19.jpg",
    status: "available",
    price: 75.0,
    description: "A crystal-embedded floral necklace for a chic style.",
  },
  {
    id: "NL020",
    name: "Amethyst Aura",
    image: "/assets/necklace20.jpg",
    status: "available",
    price: 180.25,
    description: "An enchanting amethyst stone necklace for a mystical appeal.",
  },
];
